### ISSUE TITLE
Movement/Turning speed affected by frame rate

### ISSUE THREAD

**Issue by laundmo** [bonsairobo/smooth-bevy-cameras#24]
Movement/Turning (at least using the FPS camera) is heavily dependent on Framerate:

Pay attention to the FPS counter in the video, and how it correlates with the camera movement and movement speed.

https://user-images.githubusercontent.com/24855949/191105564-909f7a44-4e10-4d05-9471-1c7893b28c91.mp4

(video from an example of testing large particle systems, which is why the angle is so weird as to not kill the video compression by looking at 500K particles.)

**Comment by bonsairobo** [comment]
Makes sense. I don't think there is any use of delta time in the controller code. Probably easy to fix.

**Comment by bonsairobo** [comment]
Fixed by ca1e62873a

**Comment by laundmo** [comment]
sorry, i'm only now getting back to this: after this commit all speeds are a lot slower, and now a lower frame rate causes faster movement.

I think it struggles with really high framerates because of the way smoothing works - its also framerate dependent.

**Comment by bonsairobo** [comment]
@laundmo speed slowdown is expected because the units of speed/sensitivity have changed

Input should not be framerate dependent anymore, can you provide a specific example?
