### ISSUE TITLE
override_input_system option inverted

### ISSUE THREAD

**Issue by thmxv** [bonsairobo/smooth-bevy-cameras#29]
Currently, setting the override_input_system option to false does override the input system. To avoid the override, one must set this option to true. This is pretty much the opposite of what a user would expect.

**Comment by bonsairobo** [comment]
Maybe our definitions of "override" are inverted. The intent is that the `Default` value of a controller plugin also has a `default_input_map` system to generate input events for some bindings. By setting `override=true` the `default_input_map` is no longer used so you can provide your own system to generate those input events.

**Comment by thmxv** [comment]
Indeed, that makes sense. Thanks and sorry for the misunderstanding. I somehow really thought that was a bug :/

**Comment by bonsairobo** [comment]
No worries!
