### ISSUE TITLE
Consider adding reflect trait for LookTransform

### ISSUE THREAD

**Issue by kylemiller3** [bonsairobo/smooth-bevy-cameras#39]
Use case: I have a MoveCommand. I want that move command to take LookTransform or Transform as target (I also save the original). Reflect saves me tons of time writing code. Right now I am using my own fork with reflect.

**Comment by kylemiller3** [comment]
Sorry that wasn't a very good opening. I think it should implement reflect because it is an engine component and is related to the Transform bevy type. I think it should match the capabilities of that object. Transform implements reflect and thus can be used in bevy ecosystem tools out of the box like the bevy reflect editor. So for me, I either have to write reflect impl for a wrapper class of LookTransform or maintain my own fork (unless there is some rust idea I don't know about here). There could be others, maybe perhaps Smoother, that may want to implement reflect.

**Comment by bonsairobo** [comment]
Sure, it's not hard to derive reflect.

Out of curiosity, what do you use reflection for?

**Comment by kylemiller3** [comment]
> Sure, it's not hard to derive reflect.
> 
> 
> 
> Out of curiosity, what do you use reflection for?

I have implemented a command pattern in my turn based game. The gist is I would like to do is treat LookTransform as something that is like Transform for my command. Specifically I have a T Component and need to save this T and restore it when execute and undo are called respectively. Since they are disparate types I believe I can only implement my own trait for each with boilerplate for get T set T for everything I want to cover. Alternatively if I can reflect partialeq and clone instead (I think those are the types) I can write reflect code for all T that implements this much more easily if we observe that saving and restoring for any T that is reflect is covered nicely by reflection by itself and no more details of T is needed. TLDR it saves boilerplate.

**Comment by kylemiller3** [comment]
And the other use case is reflect for this 3rd party plugin [bevy-inspector-egui](https://docs.rs/bevy-inspector-egui/latest/bevy_inspector_egui/) 

If you don't mind I can make a pr after I have tested reflection in the inspector

**Comment by kylemiller3** [comment]
I'll add a bit more context for my case:

```rs
#[derive(Clone, Debug)]
pub enum Command {
    OneWay(Box<dyn Executable>),
    Invertable(Box<dyn InvertableExecutable>),
}

impl PartialEq for Command {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::OneWay(l0), Self::OneWay(r0)) => l0
                .as_reflect()
                .reflect_partial_eq(r0.as_reflect())
                .unwrap_or_else(|| false),
            (Self::Invertable(l0), Self::Invertable(r0)) => l0
                .as_reflect()
                .reflect_partial_eq(r0.as_reflect())
                .unwrap_or_else(|| false),
            _ => false,
        }
    }
}
```

Having structs that implement reflect downstream allow for partial equality comparisons which is something I require. If I try traits I get an error that the traits are not object safe with partial eq. Reflection allows this easily as shown here and I think the alternative to traits and reflect would be to make many match statements, with manually downcasting and comparing. Reflect allows me to take care of every combination at once 👍
