### ISSUE TITLE
Limit where the camera can move

### ISSUE THREAD

**Issue by musjj** [bonsairobo/smooth-bevy-cameras#41]
Can we limit the camera so that it doesn't move beyond a certain bound? I think this would be pretty useful for 2D games.

**Comment by bonsairobo** [comment]
Sounds like something that could be implemented outside of this crate. Maybe try it yourself first and see if you can make something satisfactory.

**Comment by bonsairobo** [comment]
I could imagine having some kind of `TransformBounds` component and a system that clamps the transform into the bounds defined there.

**Comment by musjj** [comment]
I decided to just clamp the value of the position, before setting it to `target` or `eye`. I guess this is good enough.
