### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by rivertam** [bonsairobo/smooth-bevy-cameras#7]
It seems this hasn't been published on crates.io, which would make trying this a lot easier and less concerning (no worries this repo will update automatically and break my build). Additionally, not publishing means anyone could come in and publish a malicious package with the same name and new users will install it without checking. Please publish a release on crates.io!

(after going down a rabbit-hole for the last 8 hours, I'm guessing you're also running into [this issue](https://github.com/rivertam/bevy_wasm_mouse_move#please-publish-this-on-cratesio), so maybe it will have to wait until after bevy fixes that issue)

**Comment by bonsairobo** [comment]
> no worries this repo will update automatically and break my build

In practice, you can just pin to a known working revision.

But I agree this should be published. I just want to make sure to follow the official plugin guidelines before I publish.

https://github.com/bevyengine/bevy/blob/main/docs/plugins_guidelines.md

I'm going to spend a little time running through the checklist.

**Comment by bonsairobo** [comment]
[The deed is done.](https://crates.io/crates/smooth-bevy-cameras) I am planning on upgrading to bevy's main branch to use it with another project.
