### ISSUE TITLE
Bevy 0.6 update

### ISSUE THREAD

**Issue by mattbradbury** [bonsairobo/smooth-bevy-cameras#9]
I see you're working on updating the master to follow bevy 0.6.0.   

Any chance you can follow bevy tag v0.6.0 or rev 9599af2?  ( They are the same commit ).  I see you've grabbed on to a slightly newer revision.

Thanks for a great little plugin!

**Comment by bonsairobo** [comment]
[Release 0.2.0 on crates.io depends supports bevy 0.6](https://crates.io/crates/smooth-bevy-cameras/0.2.0/dependencies). The `main` branch will follow bevy main (really some relatively recent pinned revision).
